# Generated by Django 2.1.5 on 2020-03-17 13:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('model', models.FileField(upload_to='models/')),
                ('created_on', models.DateField(auto_now=True)),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classifiers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=16, null=True)),
                ('detail', models.CharField(blank=True, max_length=1024, null=True)),
                ('label', models.CharField(blank=True, max_length=1024, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Vectorizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('vector', models.FileField(upload_to='vector/')),
                ('created_on', models.DateField(auto_now=True)),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Question')),
            ],
            options={
                'verbose_name_plural': 'Vectorizers',
            },
        ),
        migrations.AddField(
            model_name='classifier',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Question'),
        ),
    ]
