# Generated by Django 2.1.5 on 2020-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
