# Generated by Django 2.1.5 on 2020-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20200317_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
